% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Jun-2015 15:27:18
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
%列主元消去法
function x =nagauss2(a,b,f)
if nargin<3
    f=0;
end
n =length(b);
a =[a,b];%augmentation
% if f==1
%     disp('交换次序');
% end
for k=1:(n-1)
    [ap,p]=max(abs(a(k:n,k)));
    p = p+k-1;
    if p>k %exchange k and p
        t= a(k,:);
        a(k,:) = a(p,:);
        a(p,:) =t;
    end
    a((k+1):n , (k+1):(n+1)) =  a((k+1):n ,(k+1):(n+1)) %elimination
                                - a((k+1):n ,k)/a(k,k)*a(k, (k+1):(n+1));
    a((k+1):n , k) = zeros(n-k,1);
    if f==0 %
        a
    end
end
x= zeros(n,1);
x(n) = a(n,(n+1)) / a(n,n);
for k = n-1:-1:1
    x(k,:) = (a(k,n+1) - a(k, (k+1):n)*x(k+1:n))/a(k,k);
end


        


